name: Deploy to Production

on:
  push:
    branches: [prod]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Request shared update
        run: |
          cd shared
          git pull origin main
          cd ..

      - name: Run tests
        run: npm test

      - name: Build application
        run: npm run build

      - name: Run E2E tests
        run: |
          # Aquí puedes agregar tests E2E antes de producción
          echo "E2E tests would run here"

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Deploy Backend to Production
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.PROD_SSH_KEY }}
          port: ${{ secrets.PROD_PORT }}
          script: |
            cd /home/be-stampia-prod
            git pull origin main
            npm install
            npm run build
            pm2 restart be-stampia-prod || pm2 start ecosystem.config.js --only be-stampia-prod

      - name: Notify Success
        if: success()
        run: |
          echo "🚀 Deployment to production successful!"
          echo "Backend: https://api.stampia.luciano-yomayel.com"
